//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlbanhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        internal List<GIABAN> gIABANs;

        public string MAHANG { get; set; }
        public string MALOAI { get; set; }
        public string TENHANG { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> SOLUONGCON { get; set; }
    }
}
