//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIABAN
    {
        public string MAGIABAN { get; set; }
        public string MAHANG { get; set; }
        public Nullable<int> GIA { get; set; }
        public string DVTINH { get; set; }
        public string NGAYBD { get; set; }
        public string NGAYKT { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
    }
}
