//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public int MASACH { get; set; }
        public string TENSACH { get; set; }
        public string TACGIA { get; set; }
        public string NHAXUATBAN { get; set; }
        public Nullable<System.DateTime> NAMXUATBAN { get; set; }
    }
}
