//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public int MASV { get; set; }
        public string TENSV { get; set; }
        public string GIOITINH { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> NAMSINH { get; set; }
    }
}
