//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUVIENSACH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacGia
    {
        public string MaTG { get; set; }
        public string TenTG { get; set; }
        public string SDT { get; set; }
    }
}
