//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_qldientu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public string cat_id { get; set; }
        public string cat_username { get; set; }
        public string cat_image { get; set; }
        public string cat_status { get; set; }
    }
}
