//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_qldientu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string pro_id { get; set; }
        public string pro_username { get; set; }
        public string pro_image { get; set; }
        public string pro_desc { get; set; }
        public Nullable<int> pro_price { get; set; }
    }
}
